name: "CI"
on:
  push:
  pull_request:
  repository_dispatch:
    types: [trigger-ci]
jobs:
  build:
    name: "build"
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v11
    - name: Add cachix kdevlab cache
      uses: cachix/cachix-action@v6
      with:
        name: kdevlab
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Add iohk hydra cache
      run: |
        mkdir -p ~/.config/nix
        touch ~/.config/nix/nix.conf
        echo "substituters = https://hydra.iohk.io" \
            >> ~/.config/nix/nix.conf
        echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" \
            >> ~/.config/nix/nix.conf
    - name: Add cachix iohk cache
      uses: cachix/cachix-action@v6
      with:
        name: iohk
    - name: Show nix config
      run: cat ~/.config/nix/nix.conf
    - name: Build default.nix
      run: |
        nix --print-build-logs build
    - name: Show builded paths
      run: |
        nix --print-build-logs path-info
