name: "CI"
on:
  push:
  pull_request:
  repository_dispatch:
    types: [trigger-ci]
jobs:
  build:
    name: "build"
    runs-on: macos-latest
    steps:
    - name: Checkout nix-dotenv
      uses: actions/checkout@v2
      with:
        path: environment
    - name: Install nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/36b27ccf777476ff6ff19e8df99d75681f820c98.tar.gz
    - name: Add cachix kdevlab cache
      uses: cachix/cachix-action@v7
      with:
        name: kdevlab
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Add iohk hydra cache
      run: |
        mkdir -p ~/.config/nix
        touch ~/.config/nix/nix.conf
        echo "substituters = https://hydra.iohk.io" \
            >> ~/.config/nix/nix.conf
        echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" \
            >> ~/.config/nix/nix.conf
    - name: Add cachix iohk cache
      uses: cachix/cachix-action@v7
      with:
        name: iohk
    - name: Show nix config
      run: cat ~/.config/nix/nix.conf
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Build default.nix
      run: |
        nix --print-build-logs build
      working-directory: environment
    - name: Show builded paths
      run: |
        nix --print-build-logs path-info
      working-directory: environment
    - name: Checkout dotfiles
      uses: actions/checkout@v2
      with:
        path: dotfiles
        repository: miuirussia/dotfiles
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        persist-credentials: true
    - name: Copy updated files
      run: |
        cp -f "./environment/sources/default.nix" "./environment/sources/sources.nix" "./environment/sources/sources.json" ./dotfiles/nix/sources
        cp -f "./environment/custom-plugins.nix" ./dotfiles/nix/programs/neovim
        cp -f "./environment/nixpkgs/mkHlsPkgs.nix" "./environment/nixpkgs/hls.nix" ./dotfiles/nix/nixpkgs
    - name: Commit updated files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic sources update
        repository: dotfiles
