name: "CI"
on:
  push:
  pull_request:
  repository_dispatch:
    types: [trigger-ci]
jobs:
  build:
    continue-on-error: true
    name: "build"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
    - uses: cachix/cachix-action@v6
      with:
        name: kdevlab
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
        mkdir -p ~/.config/nix
        touch ~/.config/nix/nix.conf
        echo "substituters = https://hydra.iohk.io" \
            >> ~/.config/nix/nix.conf
        echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" \
            >> ~/.config/nix/nix.conf
    - uses: cachix/cachix-action@v6
      with:
        name: iohk
    - run: cat ~/.config/nix/nix.conf
    - run: |
        nix --print-build-logs build
    - run: |
        nix --print-build-logs path-info
