name: "Autoupdate"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  build:
    name: "update"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v12
      - name: Install niv, jq, nix-prefetch-git, node2nix
        run: |
          nix-env -iA niv -f https://github.com/nmattia/niv/tarball/master \
            --substituters https://niv.cachix.org \
            --trusted-public-keys niv.cachix.org-1:X32PCg2e/zAm3/uD1ScqW2z/K0LtDyNV7RdaxIuLgQM=
          nix-env -iA jq nix-prefetch-git nodePackages.node2nix \
            -f https://github.com/NixOS/nixpkgs/archive/6f7e39c768442fce08646c3fbccacb2808baff66.tar.gz
      - name: Update dependencies
        run: |
          niv -s sources/sources.json update
          ./fix-sha256.sh hls-stable
          ./fix-sha256.sh hls-unstable
          cd nixpkgs/nodePackages && node2nix -i node-packages.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Automatic sources update
      - name: Start build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: trigger-ci
