name: "Autoupdate"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    name: "update"
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Install niv, jq, nix-prefetch-git, node2nix
        run: |
          nix-env -iA niv -f https://github.com/nmattia/niv/tarball/master \
            --substituters https://niv.cachix.org \
            --trusted-public-keys niv.cachix.org-1:X32PCg2e/zAm3/uD1ScqW2z/K0LtDyNV7RdaxIuLgQM=
          nix-env -iA jq nix-prefetch-git nodePackages.node2nix -f https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
      - name: Update dependencies
        run: |
          niv -s sources/sources.json update
          $GITHUB_WORKSPACE/fix-sha256.sh hls-stable
          $GITHUB_WORKSPACE/fix-sha256.sh hls-unstable
          cd $GITHUB_WORKSPACE/nixpkgs/vscode && ./update-vscode-plugins.py
          cd $GITHUB_WORKSPACE/nixpkgs/vscode/codelldb && ./update.sh
          cd $GITHUB_WORKSPACE/nixpkgs/nodePackages && node2nix -i node-packages.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Automatic sources update – ${{ steps.current-time.outputs.formattedTime }}
      - name: Notify in telegram
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          chatId: ${{ secrets.TELEGRAM_BOT_CHANNEL }}
          botToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
