name: "Autoupdate"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  build:
    continue-on-error: true
    name: "update"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
      - run: |
          nix-env -iA niv -f https://github.com/nmattia/niv/tarball/master \
            --substituters https://niv.cachix.org \
            --trusted-public-keys niv.cachix.org-1:X32PCg2e/zAm3/uD1ScqW2z/K0LtDyNV7RdaxIuLgQM=
      - run: |
          niv -s sources/sources.json update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: bump
           file_pattern: sources/sources.json
