name: "Autoupdate"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  build:
    name: "update"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v11
      - name: Install niv
        run: |
          nix-env -iA niv -f https://github.com/nmattia/niv/tarball/master \
            --substituters https://niv.cachix.org \
            --trusted-public-keys niv.cachix.org-1:X32PCg2e/zAm3/uD1ScqW2z/K0LtDyNV7RdaxIuLgQM=
      - name: Update dependencies
        run: |
          niv -s sources/sources.json update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: bump
           file_pattern: sources/sources.json
      - name: Start build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: trigger-ci
