name: "Autoupdate"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  build:
    continue-on-error: true
    name: "update"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
      - uses: cachix/cachix-action@v6
        with:
          name: kdevlab
      - run: |
          mkdir -p ~/.config/nix
          touch ~/.config/nix/nix.conf
          echo "substituters = https://hydra.iohk.io" \
              >> ~/.config/nix/nix.conf
          echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" \
              >> ~/.config/nix/nix.conf
      - uses: cachix/cachix-action@v6
        with:
          name: iohk
      - run: cat ~/.config/nix/nix.conf
      - run: |
          nix-shell --run 'niv -s "./sources/sources.json" update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: sources/sources.json

